[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "14"
  NPM_VERSION = "7"

[[redirects]]
  from   = "/elbisualp/js/script.js"
  to     = "https://plausible.io/js/plausible.outbound-links.js"
  status = 200

[[redirects]]
  from   = "/elbisualp/api/event"
  to     = "https://plausible.io/api/event"
  status = 202
